# Generated by Django 6.1.1 on 2026-10-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.carrito'),
        ),
        migrations.AddField(
            model_name='itemcarrito',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.curso'),
        ),
        migrations.AddConstraint(
            model_name='itemcarrito',
            constraint=models.UniqueConstraint(fields=('carrito', 'curso'), name='carrito_curso_unico'),
        ),
    ]
