# Generated by Django 6.1.1 on 2026-10-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('objetivos', models.TextField(blank=True)),
                ('cupos', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('fecha_limite_inscripcion', models.DateTimeField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicado', 'Publicado'), ('iniciado', 'Iniciado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='borrador', max_length=15)),
                ('version_cupos', models.PositiveIntegerField(default=0, editable=False)),
            ],
        ),
    ]
