# Generated by Django 6.1.1 on 2026-10-05 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(blank=True, related_name='cursos_dictados', to=settings.AUTH_USER_MODEL),
        ),
    ]
