# Generated by Django 6.1.1 on 2026-10-05 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='orders.orden'),
        ),
        migrations.AddField(
            model_name='pago',
            name='orden',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pago', to='orders.orden'),
        ),
        migrations.AddConstraint(
            model_name='itemorden',
            constraint=models.UniqueConstraint(fields=('orden', 'curso'), name='orden_curso_unico'),
        ),
    ]
